// DADOS COMPLETOS DA MATRIZ DE RISCO - 274 REGISTROS
const riskData = [
{
    id: "I-205",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Ruído contínuo",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor auricular, óculos de proteção, luva de raspa",
    controls: "Área delimitada, sinalização, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-15, NR-23, PO-002110"
},
{
    id: "I-206",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com amortecimento, luva antivibração",
    controls: "Limitação do tempo de exposição, pausas programadas, treinamento, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-207",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Vestimenta adequada, protetor solar, óculos de proteção",
    controls: "Pausas em ambiente climatizado, hidratação constante, monitoramento térmico, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-208",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor solar, óculos escuros, chapéu, vestimenta adequada",
    controls: "Evitar exposição nos horários de pico, pausas em área coberta, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-209",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção com filtro UV, máscara de solda, avental de couro",
    controls: "Área isolada, sinalização adequada, cortinas de proteção, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-210",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção, vestimenta adequada",
    controls: "Sistema de exaustão, umidificação do ambiente, ventilação forçada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-211",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira metálica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, sistema de aspiração, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-212",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de gases ácidos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara com filtro químico, óculos de proteção",
    controls: "Monitoramento atmosférico, ventilação forçada, área ventilada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-213",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de fumos metálicos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, monitoramento, sistema de exaustão, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-214",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura de pé por longos períodos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades, assentos auxiliares, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-215",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura restrita de longa duração",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas, rodízio de funções, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-216",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Botas de segurança, luvas de couro, vestimenta adequada",
    controls: "Manutenção da área limpa, inspeção prévia, controle de pragas, PO-002110",
    legislation: "NR-31, PO-002110"
},
{
    id: "I-217",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Energia elétrica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de borracha, botas isolantes, capacete dielétrico",
    controls: "Bloqueio e etiquetagem, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-10, PO-002110"
},
{
    id: "I-218",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luva de raspa, óculos de proteção, avental de couro, calçado de segurança",
    controls: "Área isolada, extintores disponíveis, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-23, PO-002110"
},
{
    id: "I-219",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Objeto/ material cortante",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de malha de aço, óculos de proteção, vestimenta adequada",
    controls: "Organização do local, treinamento, sinalização, PO-002110",
    legislation: "NR-12, PO-002110"
},
{
    id: "I-220",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Impacto por Objeto Projetado",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção, capacete, protetor facial, vestimenta adequada",
    controls: "Sinalização de área, barreiras de proteção, isolamento da área, PO-002110",
    legislation: "NR-18, PO-002110"
},
{
    id: "I-221",
    area: "Manutenção Mecânica",
    location: "Moagem de Cimento",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Cinto de segurança tipo paraquedista, capacete, talabarte",
    controls: "Plataforma de trabalho, treinamento NR-35, inspeção de equipamentos, PO-002110",
    legislation: "NR-35, PO-002110"
},
{
    id: "I-222",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Ruído contínuo",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor auricular, óculos de proteção, luva de raspa",
    controls: "Área delimitada, sinalização, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-15, NR-23, PO-002110"
},
{
    id: "I-223",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com amortecimento, luva antivibração",
    controls: "Limitação do tempo de exposição, pausas programadas, treinamento, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-224",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Vestimenta adequada, protetor solar, óculos de proteção",
    controls: "Pausas em ambiente climatizado, hidratação constante, monitoramento térmico, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-225",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor solar, óculos escuros, chapéu, vestimenta adequada",
    controls: "Evitar exposição nos horários de pico, pausas em área coberta, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-226",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção com filtro UV, máscara de solda, avental de couro",
    controls: "Área isolada, sinalização adequada, cortinas de proteção, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-227",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção, vestimenta adequada",
    controls: "Sistema de exaustão, umidificação do ambiente, ventilação forçada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-228",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira metálica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, sistema de aspiração, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-229",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de gases ácidos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara com filtro químico, óculos de proteção",
    controls: "Monitoramento atmosférico, ventilação forçada, área ventilada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-230",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de fumos metálicos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, monitoramento, sistema de exaustão, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-231",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura de pé por longos períodos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades, assentos auxiliares, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-232",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura restrita de longa duração",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas, rodízio de funções, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-233",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Botas de segurança, luvas de couro, vestimenta adequada",
    controls: "Manutenção da área limpa, inspeção prévia, controle de pragas, PO-002110",
    legislation: "NR-31, PO-002110"
},
{
    id: "I-234",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Energia elétrica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de borracha, botas isolantes, capacete dielétrico",
    controls: "Bloqueio e etiquetagem, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-10, PO-002110"
},
{
    id: "I-235",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luva de raspa, óculos de proteção, avental de couro, calçado de segurança",
    controls: "Área isolada, extintores disponíveis, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-23, PO-002110"
},
{
    id: "I-236",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Objeto/ material cortante",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de malha de aço, óculos de proteção, vestimenta adequada",
    controls: "Organização do local, treinamento, sinalização, PO-002110",
    legislation: "NR-12, PO-002110"
},
{
    id: "I-237",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Impacto por Objeto Projetado",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção, capacete, protetor facial, vestimenta adequada",
    controls: "Sinalização de área, barreiras de proteção, isolamento da área, PO-002110",
    legislation: "NR-18, PO-002110"
},
{
    id: "I-238",
    area: "Manutenção Mecânica",
    location: "Moagem de Coque",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Cinto de segurança tipo paraquedista, capacete, talabarte",
    controls: "Plataforma de trabalho, treinamento NR-35, inspeção de equipamentos, PO-002110",
    legislation: "NR-35, PO-002110"
},
{
    id: "I-239",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Ruído contínuo",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor auricular, óculos de proteção, luva de raspa",
    controls: "Área delimitada, sinalização, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-15, NR-23, PO-002110"
},
{
    id: "I-240",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com amortecimento, luva antivibração",
    controls: "Limitação do tempo de exposição, pausas programadas, treinamento, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-241",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Vestimenta adequada, protetor solar, óculos de proteção",
    controls: "Pausas em ambiente climatizado, hidratação constante, monitoramento térmico, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-242",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor solar, óculos escuros, chapéu, vestimenta adequada",
    controls: "Evitar exposição nos horários de pico, pausas em área coberta, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-243",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção com filtro UV, máscara de solda, avental de couro",
    controls: "Área isolada, sinalização adequada, cortinas de proteção, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-244",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção, vestimenta adequada",
    controls: "Sistema de exaustão, umidificação do ambiente, ventilação forçada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-245",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira metálica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, sistema de aspiração, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-246",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de gases ácidos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara com filtro químico, óculos de proteção",
    controls: "Monitoramento atmosférico, ventilação forçada, área ventilada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-247",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de fumos metálicos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, monitoramento, sistema de exaustão, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-248",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura de pé por longos períodos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades, assentos auxiliares, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-249",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura restrita de longa duração",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas, rodízio de funções, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-250",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Botas de segurança, luvas de couro, vestimenta adequada",
    controls: "Manutenção da área limpa, inspeção prévia, controle de pragas, PO-002110",
    legislation: "NR-31, PO-002110"
},
{
    id: "I-251",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Energia elétrica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de borracha, botas isolantes, capacete dielétrico",
    controls: "Bloqueio e etiquetagem, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-10, PO-002110"
},
{
    id: "I-252",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luva de raspa, óculos de proteção, avental de couro, calçado de segurança",
    controls: "Área isolada, extintores disponíveis, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-23, PO-002110"
},
{
    id: "I-253",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Objeto/ material cortante",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de malha de aço, óculos de proteção, vestimenta adequada",
    controls: "Organização do local, treinamento, sinalização, PO-002110",
    legislation: "NR-12, PO-002110"
},
{
    id: "I-254",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Impacto por Objeto Projetado",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção, capacete, protetor facial, vestimenta adequada",
    controls: "Sinalização de área, barreiras de proteção, isolamento da área, PO-002110",
    legislation: "NR-18, PO-002110"
},
{
    id: "I-255",
    area: "Manutenção Mecânica",
    location: "Forno de Pozolana",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Cinto de segurança tipo paraquedista, capacete, talabarte",
    controls: "Plataforma de trabalho, treinamento NR-35, inspeção de equipamentos, PO-002110",
    legislation: "NR-35, PO-002110"
},
{
    id: "I-256",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Ruído contínuo",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor auricular, óculos de proteção, luva de raspa",
    controls: "Área delimitada, sinalização, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-15, NR-23, PO-002110"
},
{
    id: "I-257",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Vibração de Corpo Inteiro (VCI)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com amortecimento, luva antivibração",
    controls: "Limitação do tempo de exposição, pausas programadas, treinamento, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-258",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Calor (Sobrecarga térmica)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Vestimenta adequada, protetor solar, óculos de proteção",
    controls: "Pausas em ambiente climatizado, hidratação constante, monitoramento térmico, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-259",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante - Radiação Solar",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Protetor solar, óculos escuros, chapéu, vestimenta adequada",
    controls: "Evitar exposição nos horários de pico, pausas em área coberta, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-260",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Exposição à Radiação Não Ionizante- Operações de Soldagem",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção com filtro UV, máscara de solda, avental de couro",
    controls: "Área isolada, sinalização adequada, cortinas de proteção, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-261",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira mineral (contendo sílica livre cristalizada)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção, vestimenta adequada",
    controls: "Sistema de exaustão, umidificação do ambiente, ventilação forçada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-262",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de poeira metálica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, sistema de aspiração, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-263",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de gases ácidos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara com filtro químico, óculos de proteção",
    controls: "Monitoramento atmosférico, ventilação forçada, área ventilada, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-264",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Inalação de fumos metálicos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Máscara PFF2, óculos de proteção",
    controls: "Ventilação local exaustora, monitoramento, sistema de exaustão, PO-002110",
    legislation: "NR-15, PO-002110"
},
{
    id: "I-265",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura de pé por longos períodos",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Calçado de segurança com palmilha antifatiga",
    controls: "Pausas ativas, rodízio de atividades, assentos auxiliares, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-266",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Postura restrita de longa duração",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Nenhum específico",
    controls: "Ginástica laboral, pausas programadas, rodízio de funções, PO-002110",
    legislation: "NR-17, PO-002110"
},
{
    id: "I-267",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Ataque de ser vivo com peçonha",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Botas de segurança, luvas de couro, vestimenta adequada",
    controls: "Manutenção da área limpa, inspeção prévia, controle de pragas, PO-002110",
    legislation: "NR-31, PO-002110"
},
{
    id: "I-268",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Energia elétrica",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de borracha, botas isolantes, capacete dielétrico",
    controls: "Bloqueio e etiquetagem, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-10, PO-002110"
},
{
    id: "I-269",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Material/Produto Inflamável/Combustível (serviços de soldagem e corte)",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luva de raspa, óculos de proteção, avental de couro, calçado de segurança",
    controls: "Área isolada, extintores disponíveis, treinamento específico, inspeção de equipamentos, PO-002110",
    legislation: "NR-23, PO-002110"
},
{
    id: "I-270",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Contato com Objeto/ material cortante",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Luvas de malha de aço, óculos de proteção, vestimenta adequada",
    controls: "Organização do local, treinamento, sinalização, PO-002110",
    legislation: "NR-12, PO-002110"
},
{
    id: "I-271",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Impacto por Objeto Projetado",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Óculos de proteção, capacete, protetor facial, vestimenta adequada",
    controls: "Sinalização de área, barreiras de proteção, isolamento da área, PO-002110",
    legislation: "NR-18, PO-002110"
},
{
    id: "I-272",
    area: "Manutenção Mecânica",
    location: "Tombador",
    activity: "Serviços a quente com conjunto oxiacetileno - Operação de Corte",
    risk: "Queda de pessoa com diferença de nível - Trabalho em altura",
    frequency: 5,
    severity: 4,
    score: 20,
    riskLevel: "Alto",
    ppe: "Cinto de segurança tipo paraquedista, capacete, talabarte",
    controls: "Plataforma de trabalho, treinamento NR-35, inspeção de equipamentos, PO-002110",
    legislation: "NR-35, PO-002110"
}
];